name: Test the code for linting, types and tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy flake8 pytest

      # Step 4: Run mypy for type checking
      - name: Run mypy
        run: mypy src/

      # Step 5: Run flake8 for linting
      - name: Run flake8
        run: flake8 src/

      # Step 6: Run pytest on unit_tests
      - name: Run pytest
        run: pytest unit_tests/

#    # Step 7: Build the wheel if all checks pass
#    - name: Build the wheel
#      if: success()
#      run: python -m build
#
#    # Step 8: Deploy to PyPI if all checks pass
#    - name: Publish to PyPI
#      if: success()
#      uses: pypa/gh-action-pypi-publish@v1.9.1
#      with:
#        password: ${{ secrets.PYPI_API_TOKEN }}
